### ISSUE TITLE
Save and load files

### ISSUE THREAD

**Issue by haydn** [sketchbook-js/sketchbook#117]
Users need to be able to save their work to a file and open their work from a file. Those files will live in their project alongside the Sketchbook config:

```
sketchbook/config.js
sketchbook/my-design.json
sketchbook/another-design.json
```

**Comment by Mxchaeltrxn** [comment]
@haydn As discussed, some of my ideas regarding this save and load files issue.

# In this release
1. If an opened document is renamed (in the user's filesystem) while it is open in the app, saving the file should save the file as its old name.
2. CLI command available to open a certain document.
3. GUI should have a save button that lets the user save.
4. Users should be able to set the directory that the documents are saved to.
5. Handling opening a second document while a document is already open. For now, if there are unsaved changes (compare the in memory document with the one on the file system) then throw an error and prevent opening the new one.

## Optional (in this release)
1. Rename the document from within the app and have it also rename the file in the user's filesystem.

# Later
1. GUI should have a `Save as` button that will save the file somewhere inside the default directory.
1. Autosaving to ensure users don't lose data if their device crashes.
2. A GUI to handle picking a design file and renaming design files.
3. Allow storing multiple documents in memory or at least persist the ones that aren't active/open inside a temporary folder so that if a user has multiple documents open that have unsaved changes and their computer crashes, their changes are saved.

**Comment by haydn** [comment]
@Mxchaeltrxn Sorry I've been slow to reply. Thanks for writing this up!

Yep, point 1, 2 & 3 for this release sounds good. I'm thinking we can skip 4 & 5 in this release. If the user is specifying a single file to load when you launch Sketchbook those won't be relevant:

```
yarn sketchbook --file whatever/file/i/want.json
```

It's just opening and saving the exact file specified, no multi-file shenanigans. Not the best UX, but it'll work for now.

I reckon a few of the commits in this PR get us 90% of the way there:

https://github.com/sketchbook-js/sketchbook/pull/125

IIRC, it's just saving the file that hasn't been tackled (and should be a lot easier with only a single file to worry about).
